#!/usr/bin/env python

import socket
import sys
try:
    from http.server import HTTPServer
except ImportError:
    from BaseHTTPServer import HTTPServer

from spider_launcher.server import SpiderLauncherServer

try:
    port = int(sys.argv[1])
except:
    port = 8000
server_address = ('', 8000)
httpd = HTTPServer(server_address, SpiderLauncherServer)
address, port = httpd.server_address
print('Starting server on {0}'.format(httpd.server_address))
print('http://{0}:{1}'.format(
    socket.gethostbyname(socket.gethostname()), port))
print('http://{0}:{1}'.format(address, port))
httpd.serve_forever()
